name: anniqutaman
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  expressions: ^0.2.5+2  
  geolocator: ^9.0.0
  web: ^1.0.0
  math_expressions: ^2.0.0  
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_lints: ^2.0.0
  glass: ^2.0.0+1
  url_launcher: ^6.3.0
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  hijri: ^3.0.0
  audioplayers: ^6.1.0
  cloud_firestore: ^5.4.4  
  firebase_core: ^3.6.0     
  provider: ^6.0.0
  flutter_sound: ^9.16.3
  intl: ^0.19.0
   
  flutter_launcher_icons: "^0.14.1"
  video_player: ^2.9.2
  google_maps_flutter: ^2.10.0
  shared_preferences: ^2.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/1.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/1.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/1.png"
   
flutter:
  uses-material-design: true
  assets:
    - assets/
    - Images/
    - videolar/
    - lottie/